name: unity build plugins

on: 
  workflow_dispatch:
    inputs:
      websocket:
        type: choice
        options:
        - "0"
        - "1"
        - "2"
        - "3"
        default: '1'
  push:
    paths: 
      - unity/native/**
      - unity/cli/**
      - unreal/Puerts/Source/JsEnv/Private/V8InspectorImpl.cpp
      - unreal/Puerts/Source/JsEnv/Private/WebSocketImpl.cpp
      - unreal/Puerts/Source/JsEnv/Private/V8InspectorImpl.h
      - unreal/Puerts/Source/JsEnv/Private/PromiseRejectCallback.hpp
      - unreal/Puerts/ThirdParty/**
      - .github/workflows/unity_build_plugins.yml
      - .github/workflows/composites/unity-build-plugins/**
  pull_request:
    paths: 
      - unity/native/**
      - unity/cli/**
      - unreal/Puerts/Source/JsEnv/Private/V8InspectorImpl.cpp
      - unreal/Puerts/Source/JsEnv/Private/WebSocketImpl.cpp
      - unreal/Puerts/Source/JsEnv/Private/V8InspectorImpl.h
      - unreal/Puerts/Source/JsEnv/Private/PromiseRejectCallback.hpp
      - unreal/Puerts/ThirdParty/**
      - .github/workflows/unity_build_plugins.yml
      - .github/workflows/composites/unity-build-plugins/**
#    branches-ignore:
#      - 'unity-3.0.0'

env:
  RUNID: 613573412

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install NDK
        shell: bash
        run: |
          cd ~
          rm -rf ~/android-ndk-r21b
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r21b-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
      - name: BuildAndroid
        uses: ./.github/workflows/composites/unity-build-plugins/android/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
  ohos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install NDK
        shell: bash
        run: |
          cd ~
          curl -O https://repo.huaweicloud.com/harmonyos/os/4.1-Release/ohos-sdk-windows_linux-public.tar.gz
          tar xvfz ohos-sdk-windows_linux-public.tar.gz
          cd ohos-sdk/linux
          unzip -q -o -d ./ native-linux-x64-4.1.7.5-Release.zip
      - name: BuildOHOS
        uses: ./.github/workflows/composites/unity-build-plugins/ohos/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  ios:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: BuildiOS
        uses: ./.github/workflows/composites/unity-build-plugins/ios/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  osx:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: BuildOSX
        uses: ./.github/workflows/composites/unity-build-plugins/osx/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: BuildWindows
        uses: ./.github/workflows/composites/unity-build-plugins/windows/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  linux64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: BuildLinux
        uses: ./.github/workflows/composites/unity-build-plugins/linux/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: BuildWasm
        uses: ./.github/workflows/composites/unity-build-plugins/wasm/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}